package com.kery.greendaopro.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kery.greendaopro.entity.Area;
import com.kery.greendaopro.entity.TestBean;
import com.kery.greendaopro.entity.User;

import com.kery.greendaopro.dao.AreaDao;
import com.kery.greendaopro.dao.TestBeanDao;
import com.kery.greendaopro.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaDaoConfig;
    private final DaoConfig testBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AreaDao areaDao;
    private final TestBeanDao testBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        areaDao = new AreaDao(areaDaoConfig, this);
        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Area.class, areaDao);
        registerDao(TestBean.class, testBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        areaDaoConfig.clearIdentityScope();
        testBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
